name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        working-directory: {{github.workspace}}/api
        run: |
          python -m pip install -e .[extra]
          python -m pip install -e .[seed]

      - name: Migrate database
        working-directory: {{github.workspace}}/api
        run: python api/migrate.py

      - name: Run tests
        working-directory: {{github.workspace}}/api/api
        run: python -m pytest ../tests
