openapi: 3.0.0
info:
  title: "Proper-ty API"
  description: "An API providing information about properties"
  version: "1.0.0"

servers:
  - url: "/api"

components:
  schemas:
    User:
      type: "object"
      required:
        - username
      properties:
        first_name:
          type: "string"
        last_name:
          type: "string"
        username:
          type: "string"
  parameters:
    user_id:
      name: "user_id"
      description: "Id of the user to get"
      in: path
      required: true
      schema:
        type: "integer"
    limit:
      name: "limit"
      description: "Number of items to return"
      in: query
      required: false
      schema:
        type: "integer"
        default: 10
    search_key:
      name: "search_key"
      description: "Key to search for"
      in: query
      required: false
      schema:
        type: "string"
    search_value:
      name: "search_value"
      description: "Value of key to search for"
      in: query
      required: false
      schema:
        type: "string"

paths:
  /users:
    get:
      operationId: "endpoints.users.read_all"
      tags:
        - "user"
      summary: "Read the list of users"
      responses:
        "200":
          description: "Successfully read user list"
    post:
      operationId: "endpoints.users.create"
      tags:
        - "user"
      summary: "Create a new user"
      requestBody:
        description: "User object that needs to be added"
        required: true
        content:
          application/json:
            schema:
              x-body-name: "user"
              $ref: "#/components/schemas/User"
      responses:
        "201":
          description: "Successfully created user"
        "400":
          description: "Invalid user object"
  /users/{user_id}:
    get:
      operationId: "endpoints.users.read_one"
      tags:
        - "user"
      summary: "Read user by username"
      parameters:
        - $ref: "#/components/parameters/user_id"
      responses:
        "200":
          description: "Successfully read user"
        "404":
          description: "User not found"
    put:
      operationId: "endpoints.users.update"
      tags:
        - "user"
      summary: "Update user by username"
      parameters:
        - $ref: "#/components/parameters/user_id"
      requestBody:
        description: "User object that needs to be updated"
        required: true
        content:
          application/json:
            schema:
              x-body-name: "user"
              $ref: "#/components/schemas/User"
      responses:
        "200":
          description: "Successfully updated user"
        "400":
          description: "Invalid user object"
        "404":
          description: "User not found"
    delete:
      operationId: "endpoints.users.delete"
      tags:
        - "user"
      summary: "Delete user by username"
      parameters:
        - $ref: "#/components/parameters/user_id"
      responses:
        "204":
          description: "Successfully deleted user"
        "404":
          description: "User not found"
  /properties:
    get:
      operationId: "endpoints.properties.read"
      tags:
        - "properties"
      summary: "Read the list of properties"
      parameters:
        - $ref: "#/components/parameters/limit"
        - $ref: "#/components/parameters/search_key"
        - $ref: "#/components/parameters/search_value"
      responses:
        "200":
          description: "Successfully read properties list"
        "400":
          description: "Invalid request"
